### ISSUE TITLE
Improve documentation for binding customised templateflow direstory when using the container

### ISSUE THREAD

**Issue by clarkenj** [SIMEXP/giga_connectome#106]
I get the following output and error:

```
[10:48:14] INFO     {'bids_dir': PosixPath('/data/input'), 'output_dir': PosixPath('/data/output'),             workflow.py:36
                    'analysis_level': 'group', 'participant_label': None, 'work_dir':                                         
                    PosixPath('/home/nclarke/work'), 'atlas': 'ColeAnticevic12', 'denoise_strategy': 'simple',                
                    'standardize': 'zscore', 'smoothing_fwhm': 5.0, 'reindex_bids': True, 'bids_filter_file':                 
                    None, 'calculate_intranetwork_average_correlation': False, 'verbosity': 2}                                
Traceback (most recent call last):
  File "/usr/local/bin/giga_connectome", line 8, in <module>
    sys.exit(main())
  File "/code/giga_connectome/run.py", line 127, in main
    workflow(args)
  File "/code/giga_connectome/workflow.py", line 52, in workflow
    atlas = load_atlas_setting(args.atlas)
  File "/code/giga_connectome/atlas.py", line 48, in load_atlas_setting
    atlas_config = _check_altas_config(atlas)
  File "/code/giga_connectome/atlas.py", line 158, in _check_altas_config
    with open(config_path, "r") as file:
UnboundLocalError: local variable 'config_path' referenced before assignment
```
However I think it may be because I'm not understanding where to put the atlas files/ how to reference the path. Contents of my json:

```
{
    "name": "ColeAnticevic12",
    "parameters": {
        "atlas": "ColeAnticevic12Cort",
        "template": "MNI152NLin2009aAsym",
        "resolution": "03",
        "suffix": "dseg"
    },
    "desc":"12parcels",
    "templateflow_dir": "ColeAnticevic12/"
}
```

the atlas file is in `data/atlas/` and looks like 

```
atlas/
├── ColeAnticevic12
│   └── tpl-MNI152NLin2009aAsym
│       └── tpl-MNI152NLin2009aAsym_res-03_atlas-coleanticevic_desc-12parcels_dseg.nii
```

I also tried having the atlas file outside of the app and binding the path, but got the same error. Would be grateful for any pointers, thanks!

**Comment by htwangtw** [comment]
if you are using an customised atlas, you need to pass a path to the --atlas flag, and remember to mount it to the docker container

**Comment by clarkenj** [comment]
Ok, this is my command:

```
GIGA_CONNECTOME="/home/nclarke/projects/rrg-pbellec/nclarke/giga_connectome_0.4.1_CA.simg"
FMRIPREP_DIR="/lustre04/scratch/${USER}/prisme.fmriprep"
CONNECTOME_OUTPUT="/lustre04/scratch/${USER}/prisme_connectome-0.4.1"
ATLAS="/home/nclarke/projects/rrg-pbellec/nclarke/ColeAnticevic12/"

apptainer run --bind ${FMRIPREP_DIR}:/data/input --bind ${CONNECTOME_OUTPUT}:/data/output --bind ${ATLAS}:/home/nclarke/projects/rrg-pbellec/nclarke/ColeAnticevic12/ ${GIGA_CONNECTOME} --atlas ${ATLAS} --reindex-bids --denoise-strategy simple /data/input /data/output group
```

and this is the contents of the json:

```
{
    "name": "ColeAnticevic12",
    "parameters": {
        "atlas": "ColeAnticevic12Cort",
        "template": "MNI152NLin2009aAsym",
        "resolution": "03",
        "suffix": "dseg"
    },
    "desc":"12parcels",
    "templateflow_dir": "/home/nclarke/projects/rrg-pbellec/nclarke/ColeAnticevic12/ "
}
```

What am I doing wrong?

**Comment by htwangtw** [comment]
I think this is unclear documentation on my end .... When using customised atlas, you pass the path of the atlas config file to `--atlas`

**Comment by clarkenj** [comment]
It would probably be clear to someone with more experience. This is my latest attempt, same error:

```
module load apptainer
GIGA_CONNECTOME="/home/nclarke/projects/rrg-pbellec/nclarke/giga_connectome_0.4.1_CA.simg"
FMRIPREP_DIR="/lustre04/scratch/${USER}/prisme.fmriprep"
CONNECTOME_OUTPUT="/lustre04/scratch/${USER}/prisme_connectome-0.4.1"
ATLAS_DIR="/home/nclarke/projects/rrg-pbellec/nclarke/ColeAnticevic12"
ATLAS_CONFIG="/home/nclarke/projects/rrg-pbellec/nclarke/ColeAnticevic12.json"

apptainer run --bind ${FMRIPREP_DIR}:/data/input \
              --bind ${CONNECTOME_OUTPUT}:/data/output \
              --bind ${ATLAS_DIR}:/home/nclarke/projects/rrg-pbellec/nclarke/ColeAnticevic12 \
              ${GIGA_CONNECTOME} \
              --atlas /home/nclarke/projects/rrg-pbellec/nclarke/ColeAnticevic12.json \
              --reindex-bids --denoise-strategy simple /data/input /data/output group
```

and the contents of `ColeAnticevic12.json`:

```
{
    "name": "ColeAnticevic12",
    "parameters": {
        "atlas": "ColeAnticevic12Cort",
        "template": "MNI152NLin2009aAsym",
        "resolution": "03",
        "suffix": "dseg"
    },
    "desc":"12parcels",
    "templateflow_dir": "/home/nclarke/projects/rrg-pbellec/nclarke/ColeAnticevic12/"
}
```

**Comment by htwangtw** [comment]
quick update - even with the path correctly mounted, templateflow will try to connect with the network and update. I need to disable this and make a temporary docker container.

test_atlas.json
```
{
    "name": "gordon",
    "parameters": {
        "atlas": "gordon",
        "template": "MNI152NLin6Asym",
        "resolution": "03",
        "suffix": "dseg"
    },
    "desc": [
        "333"
        ],
    "templateflow_dir" : "/data/custome_templateflow"
    
}
```
my job submission script:
```
#!/bin/bash
#SBATCH --account=rrg-pbellec
#SBATCH --output=/lustre04/scratch/${USER}/logs/test_connectome.out
#SBATCH --error=/lustre04/scratch/${USER}/logs/test_connectome.out
#SBATCH --cpus-per-task=1

GIGA_CONNECTOME_VERSION=0.4.1

GIGA_CONNECTOME=/lustre03/project/6003287/containers/giga_connectome-${GIGA_CONNECTOME_VERSION}.simg
FMRIPREP_DIR=/lustre04/scratch/${USER}/abide1_fmriprep-20.2.7lts/CMU_a
CONNECTOME_OUTPUT=/lustre04/scratch/${USER}/test_connectome
WORKINGDIR=${CONNECTOME_OUTPUT}/working_directory
ATLAS_CONFIG=/lustre03/project/6003287/${USER}/test_atlas.json
ATLAS_PATH=/lustre03/project/6003287/${USER}/fmriprep-denoise-benchmark/inputs/custome_templateflow

module load apptainer/1.1.8

mkdir -p $WORKINGDIR

echo "${FMRIPREP_DIR}"
mkdir ${WORKINGDIR}
mkdir ${SLURM_TMPDIR}
mkdir ${CONNECTOME_OUTPUT}/
echo "=========${STRATEGY}========="
apptainer run \
    --bind ${FMRIPREP_DIR}:/data/input \
    --bind ${SLURM_TMPDIR}:/data/output \
    --bind ${WORKINGDIR}:/data/working \
    --bind ${ATLAS_CONFIG}:/data/test_atlas.json \
    --bind ${ATLAS_PATH}:/data/custome_templateflow \
    ${GIGA_CONNECTOME} \
    -w /data/working \
          --atlas /data/test_atlas.json \
    --denoise-strategy simple \
    --standardize zscore \
          /data/input \
    /data/output \
    group
exitcode=$?  # catch exit code
if [ $exitcode -eq 0 ] ; then rsync -rltv --info=progress2 ${SLURM_TMPDIR}/*.h5 ${CONNECTOME_OUTPUT} ; fi
```

**Comment by htwangtw** [comment]
I figured out how to make it work:
1. make sure all the templates are downloaded in your customised templateflow dir
I just moved the customised ones to my user cache `/home/${USER}/.cache/templateflow`

2. set the customised templateflow dir to null
Config:
```
{
    "name": "gordon",
    "parameters": {
        "atlas": "gordon",
        "template": "MNI152NLin6Asym",
        "resolution": "03",
        "suffix": "dseg"
    },
    "desc": [
        "333"
        ],
    "templateflow_dir" : null
    
}
```
3. use `APPTAINERENV_TEMPLATEFLOW_HOME` to set environmental variable for templateflow

job script: 
```
#!/bin/bash
#SBATCH --account=rrg-pbellec
#SBATCH --output=/lustre04/scratch/${USER}/logs/test_connectome.out
#SBATCH --error=/lustre04/scratch/${USER}/logs/test_connectome.out
#SBATCH --cpus-per-task=1


GIGA_CONNECTOME_VERSION=0.4.1

GIGA_CONNECTOME=/lustre03/project/6003287/containers/giga_connectome-${GIGA_CONNECTOME_VERSION}.simg
FMRIPREP_DIR=/lustre04/scratch/${USER}/abide1_fmriprep-20.2.7lts/CMU_a
CONNECTOME_OUTPUT=/lustre04/scratch/${USER}/test_connectome
WORKINGDIR=${CONNECTOME_OUTPUT}/working_directory
ATLAS_CONFIG=/lustre03/project/6003287/${USER}/test_atlas.json
ATLAS_PATH=/home/${USER}/.cache/templateflow
export APPTAINERENV_TEMPLATEFLOW_HOME=/templateflow

module load apptainer/1.1.8

mkdir -p $WORKINGDIR

echo "${FMRIPREP_DIR}"
if [ -d "${FMRIPREP_DIR}" ]; then
    mkdir ${WORKINGDIR}
	mkdir ${SLURM_TMPDIR}
	mkdir ${CONNECTOME_OUTPUT}/
	echo "=========${STRATEGY}========="
	apptainer run \
	    --bind ${FMRIPREP_DIR}:/data/input \
	    --bind ${SLURM_TMPDIR}:/data/output \
	    --bind ${WORKINGDIR}:/data/working \
	    --bind ${ATLAS_CONFIG}:/data/test_atlas.json \
	    --bind ${ATLAS_PATH}:/templateflow \
	    ${GIGA_CONNECTOME} \
	    -w /data/working \
       	    --atlas /data/test_atlas.json \
	    --denoise-strategy simple \
	    --standardize zscore \
            /data/input \
	    /data/output \
	    group
	exitcode=$?  # catch exit code
	if [ $exitcode -eq 0 ] ; then rsync -rltv --info=progress2 ${SLURM_TMPDIR}/*.h5 ${CONNECTOME_OUTPUT} ; fi
else
    echo "no preprocessed data for ${SITE}"
fi
```
