### ISSUE TITLE
How to solve ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by clarkenj** [SIMEXP/giga_connectome#53]
Hi, I have an error with OASIS I cannot figure out:

```
Traceback (most recent call last):
  File "/usr/local/bin/giga_connectome", line 8, in <module>
    sys.exit(main())
  File "/code/giga_connectome/run.py", line 111, in main
    workflow(args)
  File "/code/giga_connectome/workflow.py", line 86, in workflow
    run_postprocessing_dataset(
  File "/code/giga_connectome/postprocess.py", line 103, in run_postprocessing_dataset
    denoised_img = denoise_nifti_voxel(
  File "/code/giga_connectome/denoise.py", line 133, in denoise_nifti_voxel
    time_series_voxel = group_masker.fit_transform(
  File "/usr/local/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 157, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nilearn/maskers/base_masker.py", line 289, in fit_transform
    return self.fit(**fit_params).transform(X,
  File "/usr/local/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 157, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nilearn/maskers/base_masker.py", line 249, in transform
    return self.transform_single_imgs(imgs, confounds=all_confounds,
  File "/usr/local/lib/python3.9/site-packages/nilearn/maskers/nifti_masker.py", line 570, in transform_single_imgs
    data = self._cache(
  File "/usr/local/lib/python3.9/site-packages/joblib/memory.py", line 353, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nilearn/maskers/nifti_masker.py", line 109, in _filter_and_mask
    data, affine = _filter_and_extract(
  File "/usr/local/lib/python3.9/site-packages/nilearn/maskers/base_masker.py", line 125, in _filter_and_extract
    region_signals = cache(
  File "/usr/local/lib/python3.9/site-packages/joblib/memory.py", line 353, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nilearn/signal.py", line 616, in clean
    Q, R, _ = linalg.qr(confounds, mode='economic', pivoting=True)
  File "/usr/local/lib/python3.9/site-packages/scipy/linalg/_decomp_qr.py", line 128, in qr
    a1 = numpy.asarray_chkfinite(a)
  File "/usr/local/lib/python3.9/site-packages/numpy/lib/function_base.py", line 630, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs
```

I am running at the group level. I thought I could find the subject(s) causing the error and exclude them, but not sure I'm on the right track. I have tried:

- a little script to check if the confounds for each subject contain infs or NaNs, but this returned many subjects.
- running without the line `if [ $exitcode -eq 0 ] ; then rsync -rltv --info=progress2 ${SLURM_TMPDIR}/*.h5 ${CONNECTOME_OUTPUT} ; fi`, so that I could see at least which subjects are being processed, but no output is produced.

Next I was thinking to run at the participant level but this would take a long time so thought I would ask first in case I'm on the wrong track? Would be grateful for any pointers! Thanks

**Comment by clarkenj** [comment]
Once I excluded the first row only one subject was a problem! Thank you. I'll close this issue.
