### ISSUE TITLE
error of the app on full test

### ISSUE THREAD

**Issue by Remi-Gau** [SIMEXP/giga_connectome#96]
https://github.com/SIMEXP/giga_connectome/actions/runs/7609577691/job/20721123414?pr=95#step:3:1745

```
 #11 [6/6] RUN git submodule update --init --recursive && python3 tools/download_templates.py
#11 0.231 Submodule 'tools/mist2templateflow' (https://github.com/SIMEXP/mist2templateflow.git) registered for path 'tools/mist2templateflow'
#11 0.236 Cloning into '/code/tools/mist2templateflow'...
#11 0.552 Submodule path 'tools/mist2templateflow': checked out '4e0a2a3688f344d197e6e753ca4c9bdc9b8ed5a4'
#11 4.117 [10:17:32] INFO     Schaefer2018 exists.                download_templates.py:20
#11 4.124            INFO     DiFuMo exists.                      download_templates.py:20
#11 4.136 
#11 4.136 Dataset created in /code/tools/tmp/original_BASC
#11 4.136 
#11 4.136 Traceback (most recent call last):
#11 4.136   File "/code/tools/download_templates.py", line 58, in <module>
#11 4.136     main()
#11 4.136   File "/code/tools/download_templates.py", line 54, in main
#11 4.136     download_mist()
#11 4.136   File "/code/tools/download_templates.py", line 46, in download_mist
#11 4.136     mist2templateflow.convert_basc(
#11 4.136   File "/code/tools/mist2templateflow/mist2templateflow.py", line 125, in convert_basc
#11 4.137     dataset = fetch_atlas_basc(desc, tpl_ver, data_dir=input_dir)
#11 4.137   File "/code/tools/mist2templateflow/mist2templateflow.py", line 54, in fetch_atlas_basc
#11 4.137     filename = fetch_atlas_basc_multiscale_2015(
#11 4.137 TypeError: fetch_atlas_basc_multiscale_2015() got multiple values for argument 'data_dir'
```

**Comment by htwangtw** [comment]
We upgraded `nilearn` to `0.10.2` here but `mist2templateflow` is still using an older version of `nilearn`.
I guess we updated something with `fetch_atlas_basc_multiscale_2015`
I will check what's going on with `mist2templateflow`

**Comment by htwangtw** [comment]
It's fixed on mist2templateflow side - we just need to update on this side
